"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Filecoin',
 'project_name': 'Proof Harbor Cloud',
 'track': 'Filecoin Agentic Storage',
 'pitch': 'A proof archive that writes impact artifacts, receipts, logs, and evidence '
          'bundles to Filecoin-ready manifests and retrieval receipts.',
 'idea_titles': ['Impact Proof Archive',
                 'Private Evidence Vault',
                 'Agentic Storage Control Plane'],
 'architecture_summary': 'A storage agent writes impact artifacts, receipts, logs, and '
                         'evaluation bundles to Filecoin-ready manifests. A registry '
                         'contract stores content commitments, access policy hashes, '
                         'and retrieval receipts so the repo is ready to attach live '
                         'CID proofs later.',
 'overlap_targets': ['Octant',
                     'YieldGuard',
                     'Venice Private Agents',
                     'ERC-8004 Receipts',
                     'OpenServ',
                     'Markee'],
 'primary_contract_name': 'ProofHarborRegistry',
 'primary_python_module': 'filecoin_proofs',
 'category': 'storage',
 'daily_budget_usd': 102,
 'per_action_budget_usd': 25,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'artifact_queue',
                       'description': 'Files and proofs waiting for persistence.'},
                      {'name': 'retention_policy',
                       'description': 'Namespaces, retrieval needs, and versioning.'},
                      {'name': 'upload_plan',
                       'description': 'Upload order and receipt-anchoring bundle.'},
                      {'name': 'receipts',
                       'description': 'CID mappings and verification output.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for ProofHarborRegistry.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'filecoin_proofs.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'Markee',
               'docs_url': 'https://markee.xyz/',
               'env_vars': ['MARKEE_API_KEY', 'MARKEE_MESSAGE_URL'],
               'endpoint_env': 'MARKEE_MESSAGE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish GitHub-adjacent build stories and repo messages.'}],
 'actions': [{'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 90,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'markee_repo_message',
              'target': 'markee',
              'purpose': 'Use Markee for a bounded action in this repo.',
              'partner': 'Markee',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 75,
              'sensitivity': 'low',
              'notes': ['Call Markee only after a dry-run artifact exists.',
                        'Use https://markee.xyz/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
